### ISSUE TITLE
Customizing citation-label

### ISSUE THREAD

**Issue by bwiernik** [Juris-M/propachi-vanilla#4]
@fbennett citeproc-js currently has the formatting for `citeproc.opt.trigraph` property defaulting to `Aaaa00:AaAa00:AaAA00:AAAA00`. Since neither Zotero nor Mendeley (nor other users of citeproc-js) provide users with an option to customize the trigraph format, would it perhaps be beneficial to add this as an option to Propachi?

This would be a bit more difficult than the Uppercase Subtitles option, because it would involve changing the value of a key, rather than simply cycling back and forth between two fixed values (which we currently do for Uppercase Subtitles by switching between two versions of the citeproc-js file).

It would be possible to edit the saved citeproc.js files to replace the saved trigraph key, then reload the Citeproc setting in Zotero with the new file. Do you have a more elegant idea? Or think this is best avoided altogether?

**Comment by fbennett** [comment]
The pattern can be customized in Juris-M by setting a hidden preference `csl.trigraphFormat`, which is validated before it's thrown at the processor. I think I suggested adding the preference in Zotero long ago, when that code was first written, but there were objections that it would be too hard to understand, and it never went anywhere.

If someone needs to customize the key, you can recommend that they use Juris-M and tinker with that preference. (For mainstream support on other issues, they should keep a Zotero installation in parallel, so that they don't get kicked away when submitting debug reports.)
